//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.AlbumDetails = new HashSet<AlbumDetail>();
        }
    
        public string AlbumId { get; set; }
        public string CreatedUserId { get; set; }
        public string AlbumName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<AlbumDetail> AlbumDetails { get; set; }
    }
}
