//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumDetail
    {
        public int Id { get; set; }
        public string AlbumId { get; set; }
        public string PostedUserId { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string Url { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual User User { get; set; }
    }
}
