//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEvent
    {
        public string EventID { get; set; }
        public string EventTitle { get; set; }
        public System.DateTime EventDate { get; set; }
        public string UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
