//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatReply
    {
        public int Id { get; set; }
        public string ChatBoxId { get; set; }
        public string UserIdReply { get; set; }
        public string Content { get; set; }
        public System.DateTime SendDate { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ChatBox ChatBox { get; set; }
        public virtual ChatBox ChatBox1 { get; set; }
        public virtual ChatBox ChatBox2 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
