//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cyber_Notification
    {
        public string UserID { get; set; }
        public string NotificationID { get; set; }
        public int NotificationTypeID { get; set; }
        public string NotificationContent { get; set; }
        public System.DateTime NotificationDate { get; set; }
        public bool Seen { get; set; }
    
        public virtual Cyber_Notification_Type Cyber_Notification_Type { get; set; }
        public virtual Cyber_User Cyber_User { get; set; }
    }
}
