//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cyber_Comment
    {
        public Cyber_Comment()
        {
            this.Cyber_Like = new HashSet<Cyber_Like>();
        }
    
        public string PostID { get; set; }
        public string CommentID { get; set; }
        public string CommentContent { get; set; }
        public System.DateTime CommentedDate { get; set; }
        public string CommentedBy { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual Cyber_Post Cyber_Post { get; set; }
        public virtual Cyber_User Cyber_User { get; set; }
        public virtual ICollection<Cyber_Like> Cyber_Like { get; set; }
    }
}
