//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cyber_Visible_Type
    {
        public Cyber_Visible_Type()
        {
            this.Cyber_Post = new HashSet<Cyber_Post>();
        }
    
        public int VisibleTypeID { get; set; }
        public string VisibleTypeName { get; set; }
    
        public virtual ICollection<Cyber_Post> Cyber_Post { get; set; }
    }
}
