//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cyber_Notification_Type
    {
        public Cyber_Notification_Type()
        {
            this.Cyber_Notification = new HashSet<Cyber_Notification>();
        }
    
        public int NotificationTypeID { get; set; }
        public string NotificationTypeName { get; set; }
    
        public virtual ICollection<Cyber_Notification> Cyber_Notification { get; set; }
    }
}
