//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cyber_User
    {
        public Cyber_User()
        {
            this.Cyber_Comment = new HashSet<Cyber_Comment>();
            this.Cyber_Friend1 = new HashSet<Cyber_Friend>();
            this.Cyber_Notification = new HashSet<Cyber_Notification>();
            this.Cyber_Post = new HashSet<Cyber_Post>();
            this.Cyber_Role = new HashSet<Cyber_Role>();
        }
    
        public string UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string About { get; set; }
        public string Address { get; set; }
        public string Relationship { get; set; }
        public string Work { get; set; }
        public string ContactNumber { get; set; }
        public string Studied { get; set; }
    
        public virtual ICollection<Cyber_Comment> Cyber_Comment { get; set; }
        public virtual Cyber_Friend Cyber_Friend { get; set; }
        public virtual ICollection<Cyber_Friend> Cyber_Friend1 { get; set; }
        public virtual Cyber_Membership Cyber_Membership { get; set; }
        public virtual ICollection<Cyber_Notification> Cyber_Notification { get; set; }
        public virtual ICollection<Cyber_Post> Cyber_Post { get; set; }
        public virtual Cyber_Profile_Photo Cyber_Profile_Photo { get; set; }
        public virtual ICollection<Cyber_Role> Cyber_Role { get; set; }
    }
}
