//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cyber_Role_Type
    {
        public Cyber_Role_Type()
        {
            this.Cyber_Role = new HashSet<Cyber_Role>();
        }
    
        public int RoleTypeID { get; set; }
        public string RoleTypeName { get; set; }
    
        public virtual ICollection<Cyber_Role> Cyber_Role { get; set; }
    }
}
