//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cyber_Profile_Photo
    {
        public string UserID { get; set; }
        public string ProfileImageUrl { get; set; }
        public string CoverImageUrl { get; set; }
    
        public virtual Cyber_User Cyber_User { get; set; }
    }
}
