//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MySetting
    {
        public string SettingID { get; set; }
        public string UserID { get; set; }
        public int DefaultMyPostVisibility { get; set; }
        public int DefaultOtherPostVisibility { get; set; }
        public bool AllowOtherToPost { get; set; }
    
        public virtual User User { get; set; }
        public virtual Visible_Type Visible_Type { get; set; }
        public virtual Visible_Type Visible_Type1 { get; set; }
    }
}
