//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationship_Type
    {
        public Relationship_Type()
        {
            this.Users = new HashSet<User>();
        }
    
        public int RelationshipID { get; set; }
        public string RelationshipName { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
