//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public string ReportID { get; set; }
        public bool ReportType { get; set; }
        public string ReportItem { get; set; }
        public string ReportContent { get; set; }
        public string Reporter { get; set; }
        public System.DateTime ReportedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
