//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_Type
    {
        public Role_Type()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public int RoleTypeID { get; set; }
        public string RoleTypeName { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
    }
}
