//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Friends = new HashSet<Friend>();
            this.Notifications = new HashSet<Notification>();
            this.Posts = new HashSet<Post>();
            this.Roles = new HashSet<Role>();
            this.Comments1 = new HashSet<Comment>();
            this.Posts1 = new HashSet<Post>();
        }
    
        public string UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDay { get; set; }
        public bool Gender { get; set; }
        public int RelationshipID { get; set; }
        public string About { get; set; }
        public string Address { get; set; }
        public string Work { get; set; }
        public string ContactNumber { get; set; }
        public string Studied { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Friend Friend { get; set; }
        public virtual ICollection<Friend> Friends { get; set; }
        public virtual Membership Membership { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual Profile_Photo Profile_Photo { get; set; }
        public virtual Relationship_Type Relationship_Type { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Comment> Comments1 { get; set; }
        public virtual ICollection<Post> Posts1 { get; set; }
    }
}
