//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visible_Type
    {
        public Visible_Type()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public int VisibleTypeID { get; set; }
        public string VisibleTypeName { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
    }
}
